[package]
name = "life"
version = "0.1.0"
edition = "2018"
authors = ["Mauricio Mejia Castro <jmauriciomejia@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
